'use client';

import Link from 'next/link';
import { useMemo } from 'react';
import StyleImage from '@/components/chat/StyleImage';
import CabinPreview from '@/components/visualizer/CabinPreview';
import { resolveBrief, type Brief } from '@/lib/brief';
import { buildSummary } from '@/lib/briefSummary';
import { BUILD_TYPES, PLACEHOLDER_PRICING, formatCAD } from '@/lib/estimate';

/**
 * The deliverable at the end of the conversation: a reference, a drawing, and
 * a planning range.
 *
 * Nothing here is generated by the model. The chatbot extracts fields; this
 * component draws and prices them with the same deterministic code the Design
 * Studio uses, so the two always agree — and `buildSummary()` produces the
 * email body from the same fields, so the screen and the inbox agree too.
 */
export default function BriefCard({
  brief,
  projectId,
  compact = false,
  onCopy,
  copied = false,
}: {
  brief: Brief;
  projectId: string;
  /** Panel layout: stacked, no outer border, no duplicate email button. */
  compact?: boolean;
  onCopy?: () => void;
  copied?: boolean;
}) {
  const resolved = useMemo(() => resolveBrief(brief), [brief]);
  const summary = useMemo(() => buildSummary(brief, projectId), [brief, projectId]);

  const type = BUILD_TYPES.find((t) => t.id === resolved.buildType)!;
  const sizeRatio = Math.min(1, Math.max(0, (resolved.sqft - type.min) / (type.max - type.min)));

  return (
    <section
      className={compact ? '' : 'animate-rise border border-ink/15 bg-white/70'}
      aria-labelledby="brief-heading"
    >
      <header className="flex flex-wrap items-baseline justify-between gap-3 border-b border-ink/12 px-6 py-5">
        <div>
          <p className="eyebrow text-ink/40">Project overview</p>
          <h3
            id="brief-heading"
            className="mt-2 font-display text-lg font-bold uppercase tracking-[-0.01em]"
          >
            {summary.typeLabel}
          </h3>
        </div>
        <div className={compact ? '' : 'text-right'}>
          <p className="eyebrow text-ink/40">Reference</p>
          <p className="mt-2 font-display text-lg font-extrabold tracking-[0.04em] text-cedar">
            {projectId}
          </p>
        </div>
      </header>

      {/* AI style reference — what it could look like */}
      <div className="border-b border-ink/12">
        <StyleImage brief={brief} />
      </div>

      {/* Schematic sketch — scale and configuration, drawn from the same fields */}
      <div className="border-b border-ink/12 bg-ink">
        <CabinPreview
          cladding={resolved.cladding}
          roof={resolved.roof}
          pitch={resolved.pitch.value}
          sqft={resolved.sqft}
          sizeRatio={sizeRatio}
          windows={Math.max(2, Math.min(8, Math.round(2 + sizeRatio * 5)))}
          hasDeck={resolved.addOns.includes('deck')}
          hasLoft={resolved.addOns.includes('loft')}
          hasFireplace={resolved.addOns.includes('fireplace')}
          scene={summary.scene}
        />
        <p className="border-t border-bone/10 px-5 py-3 text-center text-xs text-bone/45">
          Scale sketch — size and configuration, drawn from the same answers.
        </p>
      </div>

      <div className={`grid gap-px bg-ink/12 ${compact ? '' : 'sm:grid-cols-2'}`}>
        <dl className="bg-bone p-6">
          <p className="eyebrow mb-4 text-ink/40">What we captured</p>
          <div className="space-y-2.5 text-sm">
            {summary.rows.map((r) => (
              <div key={r.label} className="flex justify-between gap-4">
                <dt className="shrink-0 text-ink/45">{r.label}</dt>
                <dd className="text-right text-ink/80">{r.value}</dd>
              </div>
            ))}
          </div>
          {brief.notes && (
            <>
              <p className="eyebrow mb-3 mt-7 text-ink/40">In your words</p>
              <p className="text-sm leading-relaxed text-ink/70">{brief.notes}</p>
            </>
          )}
        </dl>

        <div className="bg-ink p-6 text-bone">
          <p className="eyebrow text-cedar">Expected price range</p>
          <p className="mt-3 font-display text-3xl font-extrabold leading-none tracking-[-0.02em]">
            {formatCAD(summary.low)}
          </p>
          <p className="mt-1 font-display text-3xl font-extrabold leading-none tracking-[-0.02em] text-bone/45">
            {formatCAD(summary.high)}
          </p>
          <p className="mt-4 text-xs leading-relaxed text-bone/50">
            Roughly {formatCAD(summary.perSqFtLow)} – {formatCAD(summary.perSqFtHigh)} per sq ft at
            this spec.
          </p>
          <p className="mt-4 text-xs leading-relaxed text-bone/60">
            A planning range, not a quote. Real numbers come after we walk the site.
          </p>
        </div>
      </div>

      <div className="flex flex-col gap-3 border-t border-ink/12 p-6 sm:flex-row">
        {compact ? (
          <button type="button" onClick={onCopy} className="btn-ghost-light w-full">
            {copied ? 'Overview copied' : 'Copy the overview'}
          </button>
        ) : (
          <>
            <a href={summary.mailto} className="btn-primary flex-1">
              Email this to us
            </a>
            <Link href="/visualizer" className="btn-ghost-light flex-1">
              Adjust it yourself
            </Link>
          </>
        )}
      </div>

      {PLACEHOLDER_PRICING && (
        <p className="border-t border-cedar bg-cedar/15 px-6 py-4 text-xs leading-relaxed" role="note">
          <strong className="font-display uppercase tracking-wider">Ryan —</strong> this range uses
          the placeholder rates in <code className="bg-ink/10 px-1.5 py-0.5">lib/estimate.ts</code>.
          Replace them with your own before launch.
        </p>
      )}
    </section>
  );
}
