'use client';

import Link from 'next/link';
import { useMemo } from 'react';
import CabinPreview from '@/components/visualizer/CabinPreview';
import { site } from '@/data/site';
import { resolveBrief, type Brief } from '@/lib/brief';
import {
  ADD_ONS,
  BUILD_TYPES,
  FINISH_LEVELS,
  PLACEHOLDER_PRICING,
  SEASONS,
  SITE_ACCESS,
  calculateEstimate,
  formatCAD,
} from '@/lib/estimate';

const INTERIOR = ['kitchen', 'bath', 'reno'];

/**
 * The deliverable at the end of the conversation: a reference number, a
 * drawing, and a planning range.
 *
 * Nothing here is generated by the model. The chatbot extracts fields; this
 * component draws and prices them with the same deterministic code the Design
 * Studio uses, so the two always agree.
 */
export default function BriefCard({ brief, projectId }: { brief: Brief; projectId: string }) {
  const resolved = useMemo(() => resolveBrief(brief), [brief]);

  const estimate = useMemo(
    () =>
      calculateEstimate({
        buildType: resolved.buildType,
        sqft: resolved.sqft,
        finish: resolved.finish,
        access: resolved.access,
        season: resolved.season,
        addOns: resolved.addOns,
      }),
    [resolved]
  );

  const type = BUILD_TYPES.find((t) => t.id === resolved.buildType)!;
  const isInterior = INTERIOR.includes(resolved.buildType);
  const sizeRatio = Math.min(
    1,
    Math.max(0, (resolved.sqft - type.min) / (type.max - type.min))
  );

  const rows = [
    { label: 'Project', value: type.label },
    { label: 'Size', value: `${resolved.sqft.toLocaleString()} sq ft` },
    { label: 'Finish', value: FINISH_LEVELS.find((f) => f.id === resolved.finish)!.label },
    ...(type.showsSeason
      ? [{ label: 'Use', value: SEASONS.find((s) => s.id === resolved.season)!.label }]
      : []),
    ...(type.showsAccess
      ? [{ label: 'Access', value: SITE_ACCESS.find((a) => a.id === resolved.access)!.label }]
      : []),
    ...(isInterior ? [] : [{ label: 'Cladding', value: resolved.cladding.label }]),
    ...(isInterior ? [] : [{ label: 'Roof', value: resolved.roof.label }]),
    ...(resolved.addOns.length
      ? [
          {
            label: 'Add-ons',
            value: resolved.addOns
              .map((id) => ADD_ONS.find((a) => a.id === id)!.label)
              .join(', '),
          },
        ]
      : []),
    ...(brief.location ? [{ label: 'Location', value: brief.location }] : []),
    ...(brief.timeline ? [{ label: 'Timeline', value: brief.timeline }] : []),
  ];

  const summary = [
    `Project reference: ${projectId}`,
    '',
    ...rows.map((r) => `${r.label}: ${r.value}`),
    '',
    `Planning range shown by the tool: ${formatCAD(estimate.low)} – ${formatCAD(estimate.high)}`,
    '(Planning range only — not a quote.)',
    ...(brief.notes ? ['', 'In their words:', brief.notes] : []),
    ...(brief.name ? ['', `Name: ${brief.name}`] : []),
    ...(brief.email ? [`Email: ${brief.email}`] : []),
  ].join('\n');

  const mailto = `mailto:${site.email}?subject=${encodeURIComponent(
    `${projectId} — ${type.label}`
  )}&body=${encodeURIComponent(summary)}`;

  return (
    <section
      className="animate-rise border border-ink/15 bg-white/70"
      aria-labelledby="brief-heading"
    >
      <header className="flex flex-wrap items-baseline justify-between gap-3 border-b border-ink/12 px-6 py-5">
        <div>
          <p className="eyebrow text-ink/40">Your project</p>
          <h3 id="brief-heading" className="mt-2 font-display text-lg font-bold uppercase tracking-[-0.01em]">
            {type.label}
          </h3>
        </div>
        <div className="text-right">
          <p className="eyebrow text-ink/40">Reference</p>
          <p className="mt-2 font-display text-lg font-extrabold tracking-[0.04em] text-cedar">
            {projectId}
          </p>
        </div>
      </header>

      {/* Visual reference */}
      <div className="border-b border-ink/12 bg-ink">
        <CabinPreview
          cladding={resolved.cladding}
          roof={resolved.roof}
          pitch={resolved.pitch.value}
          sqft={resolved.sqft}
          sizeRatio={sizeRatio}
          windows={Math.max(2, Math.min(8, Math.round(2 + sizeRatio * 5)))}
          hasDeck={resolved.addOns.includes('deck')}
          hasLoft={resolved.addOns.includes('loft')}
          hasFireplace={resolved.addOns.includes('fireplace')}
          isInterior={isInterior}
        />
        <p className="border-t border-bone/10 px-5 py-3 text-center text-xs text-bone/45">
          Visual reference — a stylised sketch from what you described, not an architectural drawing.
        </p>
      </div>

      <div className="grid gap-px bg-ink/12 sm:grid-cols-2">
        <dl className="bg-bone p-6">
          <p className="eyebrow mb-4 text-ink/40">What we captured</p>
          <div className="space-y-2.5 text-sm">
            {rows.map((r) => (
              <div key={r.label} className="flex justify-between gap-4">
                <dt className="shrink-0 text-ink/45">{r.label}</dt>
                <dd className="text-right text-ink/80">{r.value}</dd>
              </div>
            ))}
          </div>
        </dl>

        <div className="bg-ink p-6 text-bone">
          <p className="eyebrow text-cedar">Planning range</p>
          <p className="mt-3 font-display text-3xl font-extrabold leading-none tracking-[-0.02em]">
            {formatCAD(estimate.low)}
          </p>
          <p className="mt-1 font-display text-3xl font-extrabold leading-none tracking-[-0.02em] text-bone/45">
            {formatCAD(estimate.high)}
          </p>
          <p className="mt-4 text-xs leading-relaxed text-bone/50">
            Roughly {formatCAD(estimate.perSqFtLow)} – {formatCAD(estimate.perSqFtHigh)} per sq ft at
            this spec.
          </p>
          <p className="mt-4 text-xs leading-relaxed text-bone/60">
            A planning range, not a quote. Real numbers come after Ryan walks the site.
          </p>
        </div>
      </div>

      <div className="flex flex-col gap-3 border-t border-ink/12 p-6 sm:flex-row">
        <a href={mailto} className="btn-primary flex-1">
          Send this to Ryan
        </a>
        <Link href="/visualizer" className="btn-ghost-light flex-1">
          Adjust it yourself
        </Link>
      </div>

      {PLACEHOLDER_PRICING && (
        <p className="border-t border-cedar bg-cedar/15 px-6 py-4 text-xs leading-relaxed" role="note">
          <strong className="font-display uppercase tracking-wider">Ryan —</strong> this range uses
          the placeholder rates in <code className="bg-ink/10 px-1.5 py-0.5">lib/estimate.ts</code>.
          Replace them with your own before launch.
        </p>
      )}
    </section>
  );
}
